
baseURL = "https://xrealityai.com/"
languageCode = "en-us"
title = "xRealityAI"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
